46 send queue listener implementation
sravand123/KoraKaagaz pull request #22
Opened 2020-10-27 07:14 UTC by sahul343

SendQueueListener Basic implementation

2020-11-01 05:57 UTC, sravand123 requested changes
use Logger Wherever necessary

2020-11-01 05:57 UTC, sravand123 commented on src/networking/SendQueueListener.java
> +    public SendQueueListener(ConcurrentBlockingQueue<OutgoingPacket> SendQueue){
use IQueue in the parameters of the constructors

2020-11-01 05:57 UTC, sravand123 commented on src/networking/SendQueueListener.java
> +
``` return false```

2020-11-01 06:11 UTC, sravand123 requested changes

2020-11-01 06:11 UTC, sravand123 commented on src/networking/SendQueueListener.java
> +        return ( dest.length == 2 && isValidIpaddress(dest[1]) && isValidPort(dest[0]) );
The format of destination is ip:port,so this statement should be
```isValidIpaddress(dest[0]) && isValidPort(dest[1])```

2020-11-01 06:11 UTC, sravand123 commented on src/networking/SendQueueListener.java
> +        while(LanCommunicator.isRunning){
Use ```getStatus``` from LanCommunicator to check the status

2020-11-01 09:31 UTC, sahul343 commented
> use Logger Wherever necessary

Thanks. used logger whenever it is required. Have a look

2020-11-01 14:33 UTC, sravand123 approved these changes
Everything is working....Excellent Work sahul...

2020-11-01 14:33 UTC, merged

2020-11-03 17:44 UTC, sravand123 commented
![](https://github.trello.services/images/mini-trello-icon.png) [SendQueueListener](https://trello.com/c/T6ZuBaMd/5-sendqueuelistener)