Implementation of InternetCommunicator and ServerManager
sravand123/KoraKaagaz pull request #57
Opened 2020-11-10 19:36 UTC by sunny117

Fixes convict-git#96 - InternetCommunicator
Fixes convict-git#97 - ServerManager

2020-11-16 09:48 UTC, sravand123 requested changes

2020-11-16 09:48 UTC, sravand123 commented on src/networking/internet/InternetCommunicator.java
> +package networking.internet;
keep the file in the networking folder

2020-11-16 09:48 UTC, sravand123 commented on src/networking/internet/InternetCommunicator.java
> +                s = new Socket("52.66.253.179", 5000);
get the server info from communicatorFactory getServerInfo function

2020-11-16 09:48 UTC, sravand123 commented on src/networking/internet/InternetCommunicator.java
> +    private SocketListener socketListener;
It is not socketListener it should clientMessageReceiver

2020-11-16 09:48 UTC, sravand123 commented on src/networking/internet/InternetCommunicator.java
> +            socketListener = new SocketListener(processingReceiveQueue, contentReceiveQueue, dis);
Here also same It should be ClientMessageReceiver

2020-11-16 09:48 UTC, sravand123 commented on src/networking/server/ServerManager.java
> +				if (msg == "CHECK_INTERNET") {
Instead of ==  use equals
```msg.trim().equals("CHECK_INTERNET"))```

2020-11-16 09:48 UTC, sravand123 commented on src/networking/server/ServerManager.java
> +				else if (msg == "GET_CLIENT_INFO") {
same here

2020-11-16 09:48 UTC, sravand123 commented on src/networking/server/ServerManager.java
> +				e.printStackTrace();
dont use printstackTrace use logger instead

2020-11-16 09:48 UTC, sravand123 commented on src/networking/server/ServerManager.java
> +			e.printStackTrace();
here also same

2020-11-16 10:02 UTC, sravand123 commented on src/networking/server/ServerManager.java
> +		int clientID = 0;
initialise clientID to 1

2020-11-16 10:04 UTC, sravand123 commented on src/networking/internet/InternetCommunicator.java
> +    private Thread sendQueueListenerWorker;
As SendQueueListener file is going to be changed to InternetSendQueueListener update the code accordingly

2020-11-17 03:42 UTC, sunny117 commented
Made all the changes requested........ let me know if there are still any issues

2020-11-17 03:48 UTC, sunny117 commented
Made all the requested changes. Let me know if there are still any issues.

2020-11-22 14:31 UTC, merged